### PR TITLE
Updated README.md with latest install details

### PR DESCRIPTION
**Pull request by jinxo13**

### CODE REVIEW

**Comment by grantmcwilliams** [comment]
It appears we were adding largely the same text at the same time. I've added your updated TODO and my installation instructions. Please let me know if you think anything else needs added.

**Comment by jonlbauer** [comment]
Grant, just read your new readme - btw - I installed the newest version on my Boxee Box itself, not on a USB stick. Working fine...

**Comment by grantmcwilliams** [comment]
How would you like the instructions changed? I want this to be as easy as possible for people to install/update/use.

**Comment by jonlbauer** [comment]
Maybe just tell people that they can install it on either their Boxee Box itself or on a USB stick?

**Comment by jinxo13** [comment]
Hi Grant, You can copy the tag info from my changes proposed for Option 2 in this pull request. I'd replaced the http://boxeeplus.com with http://boxeed.in as well. As boxeeplus is no longer maintained.

**Comment by jinxo13** [comment]
Oh I see - you've updated the descriptor.xml file - so the tag is not required - nice.

**Comment by grantmcwilliams** [comment]
I figured it probably won't hurt anything leaving it there even if I get the app signing to work again. Unless you know otherwise.

**Comment by grantmcwilliams** [comment]
I've updated the readme again and added wiki pages. I removed the test-app tag from the descriptor and I'm able to sign packages again....

**Pull request closed without merging**
