### PR TITLE
Refactor and numerous enhancements - for testing

### PR DESCRIPTION
**Pull request by jinxo13**
- Added initial developer documentation
- Refactor of python code (added python objects for each screen)
- Added music playlists
- Added selecting audio and video streams
- Support for some channels
- Plays show themes
- Revamped config screens

### CODE REVIEW

**Comment by jonlbauer** [comment]
Cool!

**Comment by grantmcwilliams** [comment]
These are great additions. The docs will also make it easier for others to contribute. Thanks!

**Comment by jonlbauer** [comment]
Grant, I see that you merged the new code an hour ago. I'd love to try it, but I'm still getting 1.10. Does it just take a while to be downloadable, or do I need to do something special to get it?

- Thanx!
- Jon

**Comment by grantmcwilliams** [comment]
I haven't built packages for it yet. I'll try to get it done later today.

**Comment by grantmcwilliams** [comment]
It appears that boxee's app signing mechanism is broken. I was wondering when the lights would finally go out. I've put in a ticket and we'll see if anyone is there. If nobody answers or it doesn't magically fix itself then we'll have to move onto sideloading apps via USB.

**Comment by jonlbauer** [comment]
Would it be difficult for us to set up sideloading?

**Comment by grantmcwilliams** [comment]
I think the best way is to install Boxee+ so you can load apps from USB. I'd like to get the package signing issue resolved though but I've always feared the day would come when the one person who knew Boxee existed finally turned out the lights.

**Comment by jonlbauer** [comment]
Hey Grant,

I have Boxee+ installed already, and I have a usb stick formatted and ready. Can I download the new version and sideload easily? I'm not sure how to run a program from the usb.

I can appreciate that you want to get the signing to work. You want me to wait until you get an answer? (If you do...?)

I suspect that lots of Boxee Box owners have moved on. Can you tell how many people actively use Plexee?

- Thanx
- Jon

**Comment by grantmcwilliams** [comment]
Jon, 
    Try option 2 on the PlexForBoxee Readme (the main project page).  Let me know how it goes.

**Comment by jonlbauer** [comment]
Ok, but I'm not really clear on how to get the new Plexee files... Can you kindly summarize?

**Comment by jonlbauer** [comment]
If I click the "Download ZIP" button on the "master" page, is that the merged, new version?

**Comment by jonlbauer** [comment]
Ok, I downloaded the master zip, moved the files to the right directory on my Boxee, but the app doesn't show up. Sorry, can you give us a quick guide to how to do this?

**Comment by jinxo13** [comment]
Hi,

My dlink Boxee is not working at present so I could only check this on my
windows Boxee.


Can you try the following.

1. Remove the current Plexee repository and existing application from Boxee

2. Download the zip from Git, and extract locally

2. Modify the descriptor.xml file in the plexee.plexforboxee folder
Add the following above the </app> closing tag
        <test-app>true</test-app>
</app>

3. Copy only the plexee.plexforboxee folder to /data/.boxee/UserData/apps

4. Refresh the apps hopefully it should now appear

---

If it doesn't it may require a developer signature file to be generated
which makes this install option harder...

Cheers,
Hamish

Hamish McNeish
Ph: +61-(0)2-86047229
Mobile: +61-(0)4-27047058

**Comment by jonlbauer** [comment]
THANK YOU! Totally worked!

New version looks great!!!

- Jon

**Comment by jinxo13** [comment]
Great thanks Jon,

Let me know what issues/annoyances you encounter.

There were a lot of changes in this version - so I expect a few teething
issues are likely.

Cheers,
Hamish

Hamish McNeish
Ph: +61-(0)2-86047229
Mobile: +61-(0)4-27047058

**Comment by jonlbauer** [comment]
The only suggestion that comes to mind for a future version is that for the
libraries that are shared - meaning - ones that my friends have shared with
me, there's no description below each entry to show me whose library each
icon is. It's not a big deal, but it would be nice to be able to see
without going into each one...

- Thanx
- Jon

**Comment by grantmcwilliams** [comment]
Signing is working again (if I'm persistent) so any new changes can be rolled into an app in the repository again for anyone that was following this thread.

**Pull request merged**
